language: node_js
node_js:
  - lts/*

addons:
  sonarcloud:
    organization: "jsulpis-github"
    token: $SONAR_TOKEN

cache: yarn

jobs:
  include:
    - stage: "Build"
      script:
        - yarn lint
        - yarn test:coverage
        - sonar-scanner
        - yarn generate

branches:
  only:
    - master
